// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gridctl/gridctl/pkg/runtime (interfaces: WorkloadRuntime)
//
// Generated by this command:
//
//	mockgen -destination=mock_runtime_test.go -package=runtime . WorkloadRuntime
//

// Package runtime is a generated GoMock package.
package runtime

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkloadRuntime is a mock of WorkloadRuntime interface.
type MockWorkloadRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockWorkloadRuntimeMockRecorder
	isgomock struct{}
}

// MockWorkloadRuntimeMockRecorder is the mock recorder for MockWorkloadRuntime.
type MockWorkloadRuntimeMockRecorder struct {
	mock *MockWorkloadRuntime
}

// NewMockWorkloadRuntime creates a new mock instance.
func NewMockWorkloadRuntime(ctrl *gomock.Controller) *MockWorkloadRuntime {
	mock := &MockWorkloadRuntime{ctrl: ctrl}
	mock.recorder = &MockWorkloadRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkloadRuntime) EXPECT() *MockWorkloadRuntimeMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWorkloadRuntime) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWorkloadRuntimeMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWorkloadRuntime)(nil).Close))
}

// EnsureImage mocks base method.
func (m *MockWorkloadRuntime) EnsureImage(ctx context.Context, imageName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureImage", ctx, imageName)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureImage indicates an expected call of EnsureImage.
func (mr *MockWorkloadRuntimeMockRecorder) EnsureImage(ctx, imageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureImage", reflect.TypeOf((*MockWorkloadRuntime)(nil).EnsureImage), ctx, imageName)
}

// EnsureNetwork mocks base method.
func (m *MockWorkloadRuntime) EnsureNetwork(ctx context.Context, name string, opts NetworkOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureNetwork", ctx, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureNetwork indicates an expected call of EnsureNetwork.
func (mr *MockWorkloadRuntimeMockRecorder) EnsureNetwork(ctx, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureNetwork", reflect.TypeOf((*MockWorkloadRuntime)(nil).EnsureNetwork), ctx, name, opts)
}

// Exists mocks base method.
func (m *MockWorkloadRuntime) Exists(ctx context.Context, name string) (bool, WorkloadID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(WorkloadID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Exists indicates an expected call of Exists.
func (mr *MockWorkloadRuntimeMockRecorder) Exists(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockWorkloadRuntime)(nil).Exists), ctx, name)
}

// GetHostPort mocks base method.
func (m *MockWorkloadRuntime) GetHostPort(ctx context.Context, id WorkloadID, exposedPort int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostPort", ctx, id, exposedPort)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostPort indicates an expected call of GetHostPort.
func (mr *MockWorkloadRuntimeMockRecorder) GetHostPort(ctx, id, exposedPort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostPort", reflect.TypeOf((*MockWorkloadRuntime)(nil).GetHostPort), ctx, id, exposedPort)
}

// List mocks base method.
func (m *MockWorkloadRuntime) List(ctx context.Context, filter WorkloadFilter) ([]WorkloadStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]WorkloadStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWorkloadRuntimeMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWorkloadRuntime)(nil).List), ctx, filter)
}

// ListNetworks mocks base method.
func (m *MockWorkloadRuntime) ListNetworks(ctx context.Context, stack string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNetworks", ctx, stack)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNetworks indicates an expected call of ListNetworks.
func (mr *MockWorkloadRuntimeMockRecorder) ListNetworks(ctx, stack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNetworks", reflect.TypeOf((*MockWorkloadRuntime)(nil).ListNetworks), ctx, stack)
}

// Ping mocks base method.
func (m *MockWorkloadRuntime) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockWorkloadRuntimeMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockWorkloadRuntime)(nil).Ping), ctx)
}

// Remove mocks base method.
func (m *MockWorkloadRuntime) Remove(ctx context.Context, id WorkloadID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWorkloadRuntimeMockRecorder) Remove(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWorkloadRuntime)(nil).Remove), ctx, id)
}

// RemoveNetwork mocks base method.
func (m *MockWorkloadRuntime) RemoveNetwork(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNetwork", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveNetwork indicates an expected call of RemoveNetwork.
func (mr *MockWorkloadRuntimeMockRecorder) RemoveNetwork(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNetwork", reflect.TypeOf((*MockWorkloadRuntime)(nil).RemoveNetwork), ctx, name)
}

// Start mocks base method.
func (m *MockWorkloadRuntime) Start(ctx context.Context, cfg WorkloadConfig) (*WorkloadStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, cfg)
	ret0, _ := ret[0].(*WorkloadStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockWorkloadRuntimeMockRecorder) Start(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockWorkloadRuntime)(nil).Start), ctx, cfg)
}

// Status mocks base method.
func (m *MockWorkloadRuntime) Status(ctx context.Context, id WorkloadID) (*WorkloadStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, id)
	ret0, _ := ret[0].(*WorkloadStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockWorkloadRuntimeMockRecorder) Status(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockWorkloadRuntime)(nil).Status), ctx, id)
}

// Stop mocks base method.
func (m *MockWorkloadRuntime) Stop(ctx context.Context, id WorkloadID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockWorkloadRuntimeMockRecorder) Stop(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockWorkloadRuntime)(nil).Stop), ctx, id)
}
